### ISSUE TITLE
Workspace/projects?

### ISSUE THREAD

**Issue by hugows** [Klaster1/timer-5#13]
Hey,

is there a way to sort multiple projects/workspaces in this project?

Love the deisgn other than this little detail!

Thanks for this!

**Comment by Klaster1** [comment]
Thanks for asking! Can you please share the use cases you had in mind? As
much details  as possible.

Not sure if relevant, but I actually have two "workplaces" on the same
computer, one for tracking paid work and one for video games. The trick is
to use a separate browser profile for each.

**Comment by Klaster1** [comment]
@hugows sorry for the very late reply. My idea for the app was to have a very narrow scope of features and maybe a well-defined external interface, similar to the UNIX philosophy. As it stands now, localstorage can serve as such an API you can integrate with. Adding workspaces turned out very simple with a basic userscript - swap the current stored dataset and reload the app. Feel free to extend as needed.

```
// ==UserScript==
// @name     Timer workspace proof of concept
// @version  1
// @grant    none
// @match    https://klaster1.github.io/timer-5/*
// 
// ==/UserScript==

const button = document.createElement('button');
button.textContent = 'Switch workspace';
button.setAttribute('type', 'button');
button.style.position = 'fixed';
button.style.bottom = '20px';
button.style.right = '20px';
button.style.zIndex = '1000';
button.addEventListener('click', (event) => {
  const tasks = localStorage.getItem('tasks');
  const otherTasks = localStorage.getItem('otherTasks') ?? JSON.stringify({version: 1, value: []});
  localStorage.setItem('tasks', otherTasks);
  localStorage.setItem('otherTasks', tasks);
  location.reload();
});
document.body.appendChild(button);
```
